-- 4단계 DUMMY모음.sql



--/ 방문장소 tblVisitSpot
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 1, 1);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 1, 2);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 1, 3);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 2, 4);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 2, 5);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 2, 6);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 3, 7);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 3, 8);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 3, 9);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 4, 10);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 4, 11);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 4, 12);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 5, 13);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 5, 14);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 5, 15);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 6, 16);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 6, 17);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 6, 18);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 7, 19);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 7, 20);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 7, 21);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 8, 22);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 8, 23);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 8, 24);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 9, 25);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 9, 26);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 9, 27);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 10, 28);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 10, 29);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 10, 30);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 11, 31);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 11, 32);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 11, 33);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 12, 34);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 12, 35);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 12, 36);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 13, 37);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 13, 38);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 13, 39);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 14, 40);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 14, 41);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 14, 42);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 15, 43);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 15, 44);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 15, 45);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 16, 46);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 16, 47);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 16, 48);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 17, 49);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 17, 50);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 17, 51);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 18, 52);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 18, 53);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 18, 54);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 19, 55);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 19, 56);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 19, 57);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 20, 58);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 20, 59);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 20, 60);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 21, 61);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 21, 62);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 21, 63);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 22, 64);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 22, 65);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 22, 66);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 23, 67);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 23, 68);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 23, 69);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 24, 70);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 24, 71);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 24, 72);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 25, 73);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 25, 74);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 25, 75);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 26, 76);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 26, 77);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 26, 78);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 27, 79);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 27, 80);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 27, 81);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 28, 82);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 28, 83);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 28, 84);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 29, 85);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 29, 86);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 29, 87);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 30, 88);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 30, 89);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 30, 90);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 31, 91);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 31, 92);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 31, 93);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 32, 94);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 32, 95);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 32, 96);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 33, 97);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 33, 98);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 33, 99);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 34, 100);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 34, 101);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 34, 102);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 35, 103);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 35, 104);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 35, 105);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 36, 106);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 36, 107);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 36, 108);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 37, 109);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 37, 110);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 37, 111);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 38, 112);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 38, 113);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 38, 114);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 39, 115);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 39, 116);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 39, 117);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 40, 118);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 40, 119);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 40, 120);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 41, 121);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 41, 122);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 41, 123);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 42, 124);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 42, 125);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 42, 126);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 43, 127);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 43, 128);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 43, 129);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 44, 130);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 44, 131);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 44, 132);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 45, 133);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 45, 134);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 45, 135);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 46, 136);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 46, 137);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 46, 138);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 47, 139);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 47, 140);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 47, 141);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 48, 142);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 48, 143);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 48, 144);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 49, 145);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 49, 146);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 49, 147);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 50, 148);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 50, 149);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 50, 150);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 51, 151);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 51, 152);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 51, 153);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 52, 154);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 52, 155);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 52, 156);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 53, 157);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 53, 158);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 53, 159);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 54, 160);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 54, 161);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 54, 162);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 55, 163);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 55, 164);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 55, 165);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 56, 166);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 56, 167);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 56, 168);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 57, 169);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 57, 170);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 57, 171);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 58, 172);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 58, 173);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 58, 174);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 59, 175);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 59, 176);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 59, 177);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 60, 178);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 60, 179);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 60, 180);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 61, 181);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 61, 182);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 61, 183);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 62, 184);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 62, 185);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 62, 186);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 63, 187);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 63, 188);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 63, 189);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 64, 190);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 64, 191);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 64, 192);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 65, 193);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 65, 194);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 65, 195);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 66, 196);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 66, 197);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 66, 198);
insert into tblVisitSpot(seq, tourDateSeq, tourSpotSeq) values (seqVisitSpot.nextVal, 67, 199);




--/ 원격투어리뷰 tblControlReview
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 1, 9, '홍콩 랜선투어가 너무 좋아서 다시 또 참여하게 되었어요. 홍콩여행 짝궁 마카오로요!!ㅋㅋㅋㅋ저는 마카오를 여러번 여행해봤었지만 같이 참여한 남자친구는 마카오를 한번도 가보지 못한 마카오초심자(?)였습니다. 마카오에 대한 아무고또 모르는 남자친구가 이번 랜선투어를 통해 마카오에 넘 가보고싶다고 할 정도로 맥스 가이드님이 마카오의 핵심관광지만 쏙쏙 잘 보여주셔서 넘 좋았습니다🧡', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 2, 10, '여행을 가고 싶은데 코로나로 인해 가지 못한지 벌써 일 년이 다 돼가는 와중에 우연히 랜선 투어를 알게 되었어요. 예전에 홍콩 여행을 다녀왔는데, 이때 시간이 촉박해서 마카오는 들리지 못해 항상 가고 싶은 마음이 있어 랜선 투어를 신청', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 3, 8, '투어를 예약할때 후기가 하나도 없어서 걱정했었는데... 어제 제가 들은 투어가 첫번째 투어였더라고요 ㅋㅋ 아니...가이드님 얼마나 노련하신지... 1시간 30분 동안 시간 가는줄 모르고초집중해서 봤습니다ㅋㅋ', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 4, 8, '직접 가서 본듯한느낌을 받을수있어 너무 좋았고 차근차근 설명을 너무 잘해주셔서 다음에 직접가도 혼자 다닐수있을거 같아요 현지에서 내가 걷는듯한 느낌까지 받으니 너무 좋았어요 마카오가면 가이드님 꼭 만나고싶어요 친해진기분? ㅋㅋ', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 5, 9, '랜선투어를 처음 접해봤습니다. 실제로 걷는듯한 생동감과 사진촬영스팟, 거기에 여러가지 설명까지 기대한거보다 좋았습니다. 다음에 다른 코스를 더 추가해주신다고 하시든데, 기대되네요. 맥스가이드님 감사했어요~~', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 6, 8, '이제 마카오를 가면 꼭 같이 동행하고 싶은 가이드님을 알게 되어 너무 기쁩니다! 머지 않은 장래에 직접 만나뵙고 육포를 뜯으며 분수 쇼를 같이 바라보게 되리라 믿어 의심치 않습니다! 지둘리세요, 맥스 가이드님!', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 7, 9, '집에서 모바일로 여행해도 현장감느껴지고 설명도 재미있게해주셔서 시간이 순식간에 갔어요~^^ 세비야 정말 가보고싶게만들어주시네요~', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 8, 7, '세비야의 추억.. 좋아요', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 9, 10, '랜선투어에 입문한지 얼마 안되지만, 가보지 못한 곳보다는 가봤던 곳을 랜선투어 하는 게 훨씬 재밌더라구요. 일요일밤 홍콩 야경 투어를 먼저 신청해 두었는데 과거에 홍콩에서 잠시 마카오로 건너가 몇 시간 놀다 온 기억에 마카오도 같이 신청하게 되었습니다. 가이드 님께서 알차게 준비하신 것도 느껴지고, 하나라도 많이 보여주려 하시고, 많이 알려 주려고 노력하시는 게 전해져 정말 감사히 시청했습니다', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 10, 7, '랜선투어가 처음이라 기대를 별루 안하고 있었는데 2년전 친구들과 여행갔던 추억에 젖어 너무 좋은시간 보냈어요~ 가이드분 목소리도 좋아서 집중되더라구요^^ 다른코스도 기대중입니다ㅎ 맥스가이드님 👍', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 11, 10, '태국이라는 나라에 한 번도 가본 적이 없어서 태국은 어떤 나라인가 방콕은 어떤 곳인가 하는 마음으로 랜선투어를 신청하여 참가 하였습니다. 가이드님께서 태국에 대한 역사와 문화에 대한 자세한 설명과 더불어 핫플레이스 투어, 태국 여행 팁에 대해 자세히 알려주셔서 넘 좋았습니다.', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 12, 9, '5년전 방콕여행 했었는데, 그때와는 다른 느낌의 방콕이었어요. 즐길 수 있는 곳이 무궁무진하게 많구나를 느꼈고, 사람도 없고 어색한 방콕 이었지만 추억 할 수 있어서 좋았고 새로운 방콕을 다녀온 느낌이라 인상깊었네요. 안내도 좋았습니다.', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 13, 7, '역시 방콕에서 오래 사신 현지밀착형 가이드님이시라 뻔한 동선이 아닌 아기자기한 코스를 시간을 초과해 가면서 성의있게 진행해 주셔서 방콕의 이었습니다! 여행제한이 풀리면 바로 뵈러 갈게요! 고맙습니다!', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 14, 10, '실시간으로 안내를 받으니 실제로 여행하는 느낌으로 아주 만족하였습니다. 가이드분의 전문지식 및 적극성과 친절함이 인상깊었습니다. 프로그램도 만족스러웠습니다', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 15, 7, '방콕하면 왕궁과 수상시장이 먼저 떠오르는데 또 다른 방콕을 보여주는 코스라 즐거웠습니다 알렉스 페이스 포르투칼대사관의 빌스 그래피티 멋졌어요 좋은날이 오면 천천히 골목을 걷고 짜오프라야강 일몰을 보고 싶어요', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 16, 10, '현장감이 있어 좋았음 도보 이동의 한계로 스페인광장을 영상으로 밖에 못봐서 아쉬움 도보와 10분이내거리는 차량으로 이동해서 근처 꼭 볼만한 관광지는 소개해줬으면 합니다.', '2021-01-20');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 17, 8, '깨알지식을 많이 얻을수 있어요! 예쁜 풍경을 잘 담아주십니다.', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 18, 8, '짜임세 있게 구성된 세비야 구시가지 투어 동선과 김호영가이드님의 자세한 설명으로 인해 투어시간이 눈 깜짝할 사이에 지나간 듯 합니다. 더하여 영상의 질도 훌륭하고 촬영구도 역시 좋아 투어의 즐거움을 배가시키네요. ', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 19, 7, '집에서 모바일로 여행해도 현장감느껴지고 설명도 재미있게해주셔서 시간이 순식간에 갔어요~^^ 세비야 정말 가보고싶게만들어주시네요~', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 20, 10, '친절한 답변과 최선의 노력, 짱입니다.', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 21, 8, '너무 좋았습니다. 망설이지 말고 신청하세요 🥰 가이드님 목소리가 너무 좋고 차분하게 설명도 해주시고 소통도 해주셔서 세비야를 더 잘 느낄 수 있었어요! 인생가이드님을 만난 거 같아서 코로나 끝나고 세비야에 가게 된다면 김호영 가이드님 투어신청하려고요!', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 22, 7, '친절한 설명과, 그림 같은 뷰를 담은 카메라 앵글이 인상적이었습니다~ 다녀온 사람도, 그렇지 않은 사람도 여유롭게 즐길 수 있었어요.', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 23, 8, '현지를 걷는듣한 느낌이 드는 멋진 투어였습니다. 90분이 짧게 느껴졌어요. 랜선투어로 세비야 정취를 느낄수 있어 행복했습니다. 꼭 현지에서 가이드님 만날날이 오기를 고대해봅니다.', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 24, 7, '자세한 설명과 소소한 재미까지 유익한 투어였어요', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 25, 8, '작년에 갔던 세비야를 화면으로 다시 만날 수 있어 기뻤습니다! 당시 가지 않았던 곳도 화면으로 보니 꼭 다시 세비야를 방문해야겠다는 생각이 드네요~ 다음에는 가이드님을 세비야에서 직접 뵙고 싶습니다~!', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 26, 10, '세비야 풍경이 너무 쨍하고 예뻤어요! 가이드님 목소리도 좋으셔서 설명도 쏙쏙 들어왔고 하몽 추천감사합니다!', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 27, 7, '실시간소통, 조은설명 입니다', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 28, 10, '현지 가이드님과 실시간으로 소통하니 재밌네요~', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 29, 8, '스페인에 오래사신 가이드님 답게 세비야의 느낌을 잘 살려 설명해주셨어요. 하나라도 더 보여주시려고 시간을 더 해주신 가이드님의.정성이 돋보였습니다.', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 30, 9, '세비야의 추억.. 좋아요', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 31, 7, '가이드님 잔잔하게 유쾌하십니다. 방구석에서 오랜만에 재밌었어요! 코로나 조심하시고 다음 랜선여행에서 또 보아요 :)', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 32, 10, '지금까지 이런 여행은 없었다! 스페인 세비야를 내 집으로 가지고 오다!!', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 33, 7, '세비야가 주는 세비야만의 느낌이 있습니다. 눈에 보이는 듯한 따가운 햇살, 강렬한 오렌지나무, 구석구석 모두 다른 좁은 골목길, 쎄르베싸 한잔에 여유 누리는 노천 카페, 누군가의 열정적인 버스킹', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 34, 7, '화질이 좋고 안정적이여서 여행 프로그램을 보는 기분이 들기도 하고 실시간으로 소통하니 세비야를 실제로 여행하는 기분을 느낄 수 있었습니다. 1시간 30분이 짧게 느껴질 정도로 알찬 투어였구요, 중간중간 지루하지 않게 해주시는 영상 자료와 설명이 인상적이였습니다. ', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 35, 9, '코로나로 항상 드라마만 보는 데이트를 해서 새로운걸 해보고싶어 신청했는데 너무 좋았어요~~ 가이드분이 댓글도 하나하나 읽어주시고 설명도 잘해주셔서 같이 여행하는 기분이었습니다 ㅎㅎㅎ 화질이나 음질도 큰 문제없이 좋았어요', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 36, 8, '설명과 댓글에 대한 호응도 좋으셔서 참여하는 동안 기분이 좋고 설레었습니다~', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 37, 9, '랜선여행이었지만 세비야에 대한 흥미를 유발하기에 충분했다고 생각됩니다 호영가이드님 설명도 친절하며 동시에 흥미로웠고 세비야의 이발사에 나오는 이 거리의 제일 가는 이발사의 흥겨운 노래가 들려오는 듯했네요', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 38, 8, '세비야가 이렇게 멋진 도시인 줄 몰랐습니다. 가이드님과 실시간 채팅으로 소통하면서 세비야 구석구석 구경하는데 비록 모니터 화면이지만 현장감이 느껴져서 좋았습니다. 오렌지빛과 푸른 하늘이 빛나는 세비야, 코로나만 종식되면 꼭 가볼 1순위 여행지가 되었네요 ㅎㅎ', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 39, 9, '랜선투어 좋습니다', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 40, 9, '세비야가 이렇게 멋진 도시인 줄 몰랐습니다. 가이드님과 실시간 채팅으로 소통하면서 세비야 구석구석 구경하는데 비록 모니터 화면이지만 현장감이 느껴져서 좋았습니다. 오렌지빛과 푸른 하늘이 빛나는 세비야, 코로나만 종식되면 꼭 가볼 1순위 여행지가 되었네요 ㅎㅎ', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 41, 10, '티비에 연결해서 보니 정말 생생하게 현지느낌을 받을수 있었습니다. 대신 라이브라 긴 코스가 아닌 짧고 설명 위주라 약간 아쉬움이 있었습니다', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 42, 9, '상세한 설명 좋아요^^', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 43, 10, '랜선투어가 처음이었는데 가족들과 매우 흥미롭게 보았습니다. 가이드님의 열정적인 설명과 영상구도, 음악, 내용. 현지의 상황을 바로 느낄수 있다는점도 좋았습니다. 어서 코로나가 끝나고 직접가서 보고싶지만, 그때까지는 랜선투어로 그리움을 달랠수 있을것같아요. ^^', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 44, 9, '현지 날씨도 너무 좋았고 무엇보다 세비야를 진심으로 사랑하는 김호영 가이드님의 마음과 태도가 고스란히 전해지는 멋진 투어였어요', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 45, 8, '화질은 기대안했었는데, 엄청 좋았습니다. 유투브 유명 크리에이터 내지 TV방송프로그램 정도 였구요, 가이드님 설명도 재미있어서 현지투어를 한 느낌이었습니다…', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 46, 7, '가이드님께서 천천히 걸으면서 카메라로 오렌지 나무 한 그루, 벤치 하나도 자세히 비취주셔서 세비야 골목의 현장감을 충분히 느낄수 있어서 너무 좋았어요~ 채팅에 올린 글들도 신속하게 확인하고 소통해주신 점도 좋았구요~ ', '2021-01-21');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 47, 8, '일년에 한번씩 겨울마다 스페인 여행을 간지 6년째인데 올해는 코로나로 여행도 못가고 너무 슬픈 한 해였네요. 우연히 인스타 광고에 랜선투어가 있는걸 보고 저의 최애도시 세비야 여행상품을 골라 투어하게 되었습니다.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 48, 9, '친절한 가이드 설명과 영상으로 편하게 여행했네요 ^^', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 49, 9, '덕분에 오랜만에 즐거운 여행이 되었습니다!', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 50, 7, '쉽지 않은 랜선투어 였을텐데 수고하신 가이드님께 박수', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 51, 8, '몇일전에 라이브가 아닌 다른 가이드 상품을 구입하여 실망하였었는데 여행자후기를 읽고 평소 가고보 싶었던 세비야 라이브방송을 구매하였는데 대만족입니다.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 52, 7, '랜선투어라는 경험을 해보고자 시도를한것입니다. 대화가아닌 댓글이라는 한계가있었지만 현지의 바람소리조차 생생하게 들을수있다는것이 매우 신선했어요.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 53, 10, '랜선여행임에도 적절한 시청각 자료로 더 감동을 느낄 수 있도록 많이 도와주셔서 좋았어요~! 실시간 채팅에 센스있게 답도 잘해주시고 여러모로 즐거운 여행이었습니다! 다음 번에는 랜선여행이 아닌 실제 여행으로 김호영 가이드님과 함께 하고 싶습니다!', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 54, 7, '최고입니다. 강추 ~!!', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 55, 8, '세비야 안가봤는데, 진짜 가보고 싶어졌습니다 설명도 잘해주시고, 영상으로 최대한 잘 담아주셔서 진짜 제가 마치 보고 있는 느낌이 들었습니다. 세비야 진짜 가고싶네요. 가이드 감사합니다.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 56, 8, '직접 세비야에서 걷고 있는 느낌이었어요. 설명도 좋았고 참가자들과 소통고 많이 하셨고, 시간 안에 충실하게 세비야를 보여주고 싶어하시는 마음이 전해졌습니다. 맛있는 하몽을 술 없이 드실 땐 안타까웠네요. 세비야 안의 멋진 바 투어를 해주셔도 좋을 것 같네요.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 57, 7, '새로운경험이었습니다.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 58, 9, '여행간 느낌이여서 좋았어요ㅡ 초반에 오렌지나무 장면만 너무 오래 나와 아쉬운부분이 있었어요ㅡ 골목 골목 거리 풍경을 보여주면서 다양한이야기를 해주는게 더 낫지않았나 싶어요ㅡ', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 59, 8, '개인적으로 바르셀로나보다 세비야가 훨씬 예쁜 것 같아요. 동화 속에 나오는 곳들 같았습니다. 보통 한국 사람들이 잘 가지 않는 코스를 보여주신 것도 좋았습니다. 여태까지 본 랜선투어 중에 유일하게 먹방이 있는 것도 좋았는데 음식을 좀 더 자세히 보여주시거나 음식이 좀 더 다채로우면 좋겠어요~', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 60, 10, '가이드님이 관광장소 구석구석을 자세하게 알고 있다는 느낌이 들었습니다. 동선도 깔끔하고 좋았습니다. 랜선여행이었음에도 불구하고 세비야의 매력을 충분히 느낄 수 있었습니다. 랜선여행은 처음인데, 중간중간 관련 음악이나 동영상을 활용해주셔서 좋았습니다. ', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 61, 9, '이드 분의 친절하고 섬세한 안내가 여행의 기쁨을 배가시켜 주는 경험이었습니다', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 62, 9, '랜선 여행은 처음이었는데 신세계네요. 생각보다 너무 즐거웠습니다. 영상 전혀 흔들리지 않고 가이드님 상세한 설명 너무 좋았고, 무엇보다 가이드님이 실시간으로 소통하며 진행하셔서 그런지 현장감 넘쳤습니다. 세비야의 파란 하늘과 카르멘 OST가 잊혀지지 않네요. ', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 63, 9, '생생한 목소리를 들을 수 있어 좋았어요, 스페인 책과 비교 불가네요~~ 랜선 투어용 사진항목 신설바랍니다', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 64, 9, '가이드가 괜찮아요', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 65, 10, '홍콩 랜선투어가 너무 좋아서 다시 또 참여하게 되었어요. 홍콩여행 짝궁 마카오로요!!ㅋㅋㅋㅋ저는 마카오를 여러번 여행해봤었지만 같이 참여한 남자친구는 마카오를 한번도 가보지 못한 마카오초심자(?)였습니다. .', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 66, 10, '여행을 가고 싶은데 코로나로 인해 가지 못한지 벌써 일 년이 다 돼가는 와중에 우연히 랜선 투어를 알게 되었어요. 예전에 홍콩 여행을 다녀왔는데, 이때 시간이 촉박해서 마카오는 들리지 못해 항상 가고 싶은 마음이 있어 랜선 투어를 신청해보았는데, 생각했던 것보다 더 생동감 있고 즐겁게 봤습니다.', '2021-01-22');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 67, 8, '투어를 예약할때 후기가 하나도 없어서 걱정했었는데... 어제 제가 들은 투어가 첫번째 투어였더라고요 ㅋㅋ 아니...가이드님 얼마나 노련하신지... 1시간 30분 동안 시간 가는줄 모르고초집중해서 봤습니다ㅋㅋ', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 68, 8, '직접 가서 본듯한느낌을 받을수있어 너무 좋았고 차근차근 설명을 너무 잘해주셔서 다음에 직접가도 혼자 다닐수있을거 같아요 현지에서 내가 걷는듯한 느낌까지 받으니 너무 좋았어요 마카오가면 가이드님 꼭 만나고싶어요 친해진기분? ㅋㅋ', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 69, 9, '랜선투어를 처음 접해봤습니다. 실제로 걷는듯한 생동감과 사진촬영스팟, 거기에 여러가지 설명까지 기대한거보다 좋았습니다. 다음에 다른 코스를 더 추가해주신다고 하시든데, 기대되네요. 맥스가이드님 감사했어요~~', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 70, 7, '이제 마카오를 가면 꼭 같이 동행하고 싶은 가이드님을 알게 되어 너무 기쁩니다! 머지 않은 장래에 직접 만나뵙고 육포를 뜯으며 분수 쇼를 같이 바라보게 되리라 믿어 의심치 않습니다! 지둘리세요, 맥스 가이드님!', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 71, 8, '🤗🤗🤗😙😙🤩🤩🤩', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 72, 9, '랜선투어에 푹 빠져들고 있는 여행꾼입니다. (살짝 지각해서 채팅참여는 적극 못했어요..) 처음엔 마카오라는 곳이 어떤 특별한 경험을 줄 수 있을까 궁금한 마음에 신청해보았어요.결론만 말씀드리면 정말 만족스러웠습니다.핵심 관광지만 미리 여행하는 느낌일거라 생각했는데, 제가 실제로 참여했던 것 같은 착각마저 들게 했습니다. 가이드 선생님이 이 한시간 반을 위해 얼마나 준비하셨을지 그려집니다.후속 코스도 애타게 기다립니다. 건승하세요.', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 73, 9, '랜선투어에 입문한지 얼마 안되지만, 가보지 못한 곳보다는 가봤던 곳을 랜선투어 하는 게 훨씬 재밌더라구요.', '2021-01-23');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 74, 7, '랜선투어가 처음이라 기대를 별루 안하고 있었는데 2년전 친구들과 여행갔던 추억에 젖어 너무 좋은시간 보냈어요~ 가이드분 목소리도 좋아서 집중되더라구요^^ 다른코스도 기대중입니다ㅎ 맥스가이드님 👍', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 75, 8, '태국이라는 나라에 한 번도 가본 적이 없어서 태국은 어떤 나라인가 방콕은 어떤 곳인가 하는 마음으로 랜선투어를 신청하여 참가 하였습니다. 가이드님께서 태국에 대한 역사와 문화에 대한 자세한 설명과 더불어 핫플레이스 투어, 태국 여행 팁에 대해 자세히 알려주셔서 넘 좋았습니다. 흔한 여행 코스가 아니어서 더 좋았던 시간이었고 방콕에 대한 관심이 더 생긴 것 같고 코로나가 끝나면 방콕으로 꼭 여행 가고 싶다는 생각이 들었습니다. 방콕의 핫플레이스가 궁금하시다면 방콕 랜선 투어 참여해 보시면 좋을 것 같습니다', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 76, 7, '5년전 방콕여행 했었는데, 그때와는 다른 느낌의 방콕이었어요. 즐길 수 있는 곳이 무궁무진하게 많구나를 느꼈고, 사람도 없고 어색한 방콕 이었지만 추억 할 수 있어서 좋았고 새로운 방콕을 다녀온 느낌이라 인상깊었네요. 안내도 좋았습니다.', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 77, 7, '역시 방콕에서 오래 사신 현지밀착형 가이드님이시라 뻔한 동선이 아닌 아기자기한 코스를 시간을 초과해 가면서 성의있게 진행해 주셔서 방콕의 이었습니다! 여행제한이 풀리면 바로 뵈러 갈게요! 고맙습니다!', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 78, 10, '실시간으로 안내를 받으니 실제로 여행하는 느낌으로 아주 만족하였습니다. 가이드분의 전문지식 및 적극성과 친절함이 인상깊었습니다. 프로그램도 만족스러웠습니다', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 79, 10, '방콕하면 왕궁과 수상시장이 먼저 떠오르는데 또 다른 방콕을 보여주는 코스라 즐거웠습니다 알렉스 페이스 포르투칼대사관의 빌스 그래피티 멋졌어요 좋은날이 오면 천천히 골목을 걷고 짜오프라야강 일몰을 보고 싶어요', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 80, 7, '현장감이 있어 좋았음 도보 이동의 한계로 스페인광장을 영상으로 밖에 못봐서 아쉬움 도보와 10분이내거리는 차량으로 이동해서 근처 꼭 볼만한 관광지는 소개해줬으면 합니다.', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 81, 7, '깨알지식을 많이 얻을수 있어요! 예쁜 풍경을 잘 담아주십니다.', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 82, 7, '짜임세 있게 구성된 세비야 구시가지 투어 동선과 김호영가이드님의 자세한 설명으로 인해 투어시간이 눈 깜짝할 사이에 지나간 듯 합니다. 더하여 영상의 질도 훌륭하고 촬영구도 역시 좋아 투어의 즐거움을 배가시키네요. 세비아 꼭 한 번 여행해야 겠네요. 행복한 시간이었습니다. 감사합니다.^^', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 83, 7, '집에서 모바일로 여행해도 현장감느껴지고 설명도 재미있게해주셔서 시간이 순식간에 갔어요~^^ 세비야 정말 가보고싶게만들어주시네요~', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 84, 7, '친절한 답변과 최선의 노력, 짱입니다.', '2021-01-24');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 85, 9, '너무 좋았습니다. 망설이지 말고 신청하세요 🥰 가이드님 목소리가 너무 좋고 차분하게 설명도 해주시고 소통도 해주셔서 세비야를 더 잘 느낄 수 있었어요! 인생가이드님을 만난 거 같아서 코로나 끝나고 세비야에 가게 된다면 김호영 가이드님 투어신청하려고요!', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 86, 9, '친절한 설명과, 그림 같은 뷰를 담은 카메라 앵글이 인상적이었습니다~ 다녀온 사람도, 그렇지 않은 사람도 여유롭게 즐길 수 있었어요.', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 87, 9, '현지를 걷는듣한 느낌이 드는 멋진 투어였습니다. 90분이 짧게 느껴졌어요. 랜선투어로 세비야 정취를 느낄수 있어 행복했습니다. 꼭 현지에서 가이드님 만날날이 오기를 고대해봅니다.', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 88, 7, '자세한 설명과 소소한 재미까지 유익한 투어였어요', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 89, 7, '작년에 갔던 세비야를 화면으로 다시 만날 수 있어 기뻤습니다! 당시 가지 않았던 곳도 화면으로 보니 꼭 다시 세비야를 방문해야겠다는 생각이 드네요~ 다음에는 가이드님을 세비야에서 직접 뵙고 싶습니다~!', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 90, 10, '세비야 풍경이 너무 쨍하고 예뻤어요! 가이드님 목소리도 좋으셔서 설명도 쏙쏙 들어왔고 하몽 추천감사합니다!', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 91, 10, '실시간소통, 조은설명 입니다', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 92, 9, '현지 가이드님과 실시간으로 소통하니 재밌네요~', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 93, 8, '스페인에 오래사신 가이드님 답게 세비야의 느낌을 잘 살려 설명해주셨어요. 하나라도 더 보여주시려고 시간을 더 해주신 가이드님의.정성이 돋보였습니다.', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 94, 8, '세비야의 추억.. 좋아요', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 95, 7, '가이드님 잔잔하게 유쾌하십니다. 방구석에서 오랜만에 재밌었어요! 코로나 조심하시고 다음 랜선여행에서 또 보아요 :)', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 96, 9, '지금까지 이런 여행은 없었다! 스페인 세비야를 내 집으로 가지고 오다!!', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 97, 8, '세비야가 주는 세비야만의 느낌이 있습니다. 눈에 보이는 듯한 따가운 햇살, 강렬한 오렌지나무, 구석구석 모두 다른 좁은 골목길, 쎄르베싸 한잔에 여유 누리는 노천 카페, 누군가의 열정적인 버스킹, 자전거 타고 달리는 노을 지는 강가, 저녁이 되면 삼삼오오 모이는 타파스바', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 98, 10, '화질이 좋고 안정적이여서 여행 프로그램을 보는 기분이 들기도 하고 실시간으로 소통하니 세비야를 실제로 여행하는 기분을 느낄 수 있었습니다.', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 99, 8, '코로나로 항상 드라마만 보는 데이트를 해서 새로운걸 해보고싶어 신청했는데 너무 좋았어요~~ 가이드분이 댓글도 하나하나 읽어주시고 설명도 잘해주셔서 같이 여행하는 기분이었습니다 ㅎㅎㅎ 화질이나 음질도 큰 문제없이 좋았어요 다음에 또 해보려고요!! ', '2021-01-25');
insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 100, 8, '설명과 댓글에 대한 호응도 좋으셔서 참여하는 동안 기분이 좋고 설레었습니다~', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 101, 9, '랜선여행이었지만 세비야에 대한 흥미를 유발하기에 충분했다고 생각됩니다 호영가이드님 설명도 친절하며 동시에 흥미로웠고 세비야의 이발사에 나오는 이 거리의 제일 가는 이발사의 흥겨운 노래가 들려오는 듯했네요', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 102, 7, '세비야가 이렇게 멋진 도시인 줄 몰랐습니다. 가이드님과 실시간 채팅으로 소통하면서 세비야 구석구석 구경하는데 비록 모니터 화면이지만 현장감이 느껴져서 좋았습니다. 오렌지빛과 푸른 하늘이 빛나는 세비야, 코로나만 종식되면 꼭 가볼 1순위 여행지가 되었네요 ㅎㅎ', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 103, 9, '랜선투어 좋습니다', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 104, 8, '세비야가 이렇게 멋진 도시인 줄 몰랐습니다. 가이드님과 실시간 채팅으로 소통하면서 세비야 구석구석 구경하는데 비록 모니터 화면이지만 현장감이 느껴져서 좋았습니다. 오렌지빛과 푸른 하늘이 빛나는 세비야, 코로나만 종식되면 꼭 가볼 1순위 여행지가 되었네요 ㅎㅎ', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 105, 8, '티비에 연결해서 보니 정말 생생하게 현지느낌을 받을수 있었습니다. 대신 라이브라 긴 코스가 아닌 짧고 설명 위주라 약간 아쉬움이 있었습니다', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 106, 10, '상세한 설명 좋아요^^', '2021-01-25');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 107, 8, '랜선투어가 처음이었는데 가족들과 매우 흥미롭게 보았습니다. 가이드님의 열정적인 설명과 영상구도, 음악, 내용. 현지의 상황을 바로 느낄수 있다는점도 좋았습니다. 어서 코로나가 끝나고 직접가서 보고싶지만, 그때까지는 랜선투어로 그리움을 달랠수 있을것같아요. ^^', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 108, 7, '현지 날씨도 너무 좋았고 무엇보다 세비야를 진심으로 사랑하는 김호영 가이드님의 마음과 태도가 고스란히 전해지는 멋진 투어였어요', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 109, 8, '화질은 기대안했었는데, 엄청 좋았습니다. 유투브 유명 크리에이터 내지 TV방송프로그램 정도 였구요, 가이드님 설명도 재미있어서 현지투어를 한 느낌이었습니다…', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 110, 9, '가이드님께서 천천히 걸으면서 카메라로 오렌지 나무 한 그루, 벤치 하나도 자세히 비취주셔서 세비야 골목의 현장감을 충분히 느낄수 있어서 너무 좋았어요~ 채팅에 올린 글들도 신속하게 확인하고 소통해주신 점도 좋았구요~ 조만간 미세먼지 많고 추운 날에 세비야의 파란 하늘과 예쁜 오렌지나무 보러 다시 한번 랜선투어 가볼 생각이에요~', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 111, 10, '일년에 한번씩 겨울마다 스페인 여행을 간지 6년째인데 올해는 코로나로 여행도 못가고 너무 슬픈 한 해였네요. 우연히 인스타 광고에 랜선투어가 있는걸 보고 저의 최애도시 세비야 여행상품을 골라 투어하게 되었습니다.', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 112, 8, '친절한 가이드 설명과 영상으로 편하게 여행했네요 ^^', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 113, 8, '덕분에 오랜만에 즐거운 여행이 되었습니다!', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 114, 10, '쉽지 않은 랜선투어 였을텐데 수고하신 가이드님께 박수', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 115, 10, '몇일전에 라이브가 아닌 다른 가이드 상품을 구입하여 실망하였었는데 여행자후기를 읽고 평소 가고보 싶었던 세비야 라이브방송을 구매하였는데 대만족입니다.', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 116, 8, '랜선투어라는 경험을 해보고자 시도를한것입니다. 대화가아닌 댓글이라는 한계가있었지만 현지의 바람소리조차 생생하게 들을수있다는것이 매우 신선했어요.', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 117, 9, '랜선여행임에도 적절한 시청각 자료로 더 감동을 느낄 수 있도록 많이 도와주셔서 좋았어요~! 실시간 채팅에 센스있게 답도 잘해주시고 여러모로 즐거운 여행이었습니다! 다음 번에는 랜선여행이 아닌 실제 여행으로 김호영 가이드님과 함께 하고 싶습니다!', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 118, 9, '최고입니다. 강추 ~!!', '2021-01-26');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 119, 10, '세비야 안가봤는데, 진짜 가보고 싶어졌습니다 설명도 잘해주시고, 영상으로 최대한 잘 담아주셔서 진짜 제가 마치 보고 있는 느낌이 들었습니다. 세비야 진짜 가고싶네요. 가이드 감사합니다.', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 120, 7, '직접 세비야에서 걷고 있는 느낌이었어요. 설명도 좋았고 참가자들과 소통고 많이 하셨고, 시간 안에 충실하게 세비야를 보여주고 싶어하시는 마음이 전해졌습니다. 맛있는 하몽을 술 없이 드실 땐 안타까웠네요. 세비야 안의 멋진 바 투어를 해주셔도 좋을 것 같네요.', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 121, 7, '새로운경험이었습니다.', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 122, 7, '여행간 느낌이여서 좋았어요ㅡ 초반에 오렌지나무 장면만 너무 오래 나와 아쉬운부분이 있었어요ㅡ 골목 골목 거리 풍경을 보여주면서 다양한이야기를 해주는게 더 낫지않았나 싶어요ㅡ', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 123, 8, '개인적으로 바르셀로나보다 세비야가 훨씬 예쁜 것 같아요. 동화 속에 나오는 곳들 같았습니다. 보통 한국 사람들이 잘 가지 않는 코스를 보여주신 것도 좋았습니다. 여태까지 본 랜선투어 중에 유일하게 먹방이 있는 것도 좋았는데 음식을 좀 더 자세히 보여주시거나 음식이 좀 더 다채로우면 좋겠어요~', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 124, 10, '가이드님이 관광장소 구석구석을 자세하게 알고 있다는 느낌이 들었습니다. 동선도 깔끔하고 좋았습니다. 랜선여행이었음에도 불구하고 세비야의 매력을 충분히 느낄 수 있었습니다. 랜선여행은 처음인데, 중간중간 관련 음악이나 동영상을 활용해주셔서 좋았습니다. 코로나가 끝나면 세비야에 실제로 가보고 싶네요!', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 125, 10, '이드 분의 친절하고 섬세한 안내가 여행의 기쁨을 배가시켜 주는 경험이었습니다', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 126, 7, '랜선 여행은 처음이었는데 신세계네요. 생각보다 너무 즐거웠습니다. 영상 전혀 흔들리지 않고 가이드님 상세한 설명 너무 좋았고, 무엇보다 가이드님이 실시간으로 소통하며 진행하셔서 그런지 현장감 넘쳤습니다. 세비야의 파란 하늘과 카르멘 OST가 잊혀지지 않네요. 덕분에 친구들과 즐거운 여행 했습니다. 김호영 가이드님 다시 한번 감사드립니다.', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 127, 7, '생생한 목소리를 들을 수 있어 좋았어요, 스페인 책과 비교 불가네요~~ 랜선 투어용 사진항목 신설바랍니다', '2021-01-27');
--insert into tblControlReview (seq, controlReservationSeq, score, contents, writeDate) values (seqControlReview.nextVal, 128, 10, '가이드가 괜찮아요', '2021-01-27');
