
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 92, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-10-01', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 75, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-02-16', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 20, 19, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-11-02', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 10, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-08-04', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 86, 76, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-06-12', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 28, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-08-27', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 2, 56, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-03-07', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 49, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-08-15', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 1, 100, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-02-01', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 45, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2020-06-27', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 80, 77, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-06-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 72, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-07-19', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 80, 96, '최고의 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2019-06-20', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 39, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-05-27', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 54, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-10-25', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 34, 93, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-04-23', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 81, 79, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-09-04', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 70, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-10-09', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 68, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-01-25', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 65, '추천하지 않습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-01-21', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 73, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-02-17', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 91, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-08-29', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 52, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 주인분들에게 감사합니다.', '2019-01-22', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 68, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-05-09', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 16, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-05-08', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 3, 82, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-11-11', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 59, 92, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-10-05', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 69, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-06-10', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 52, 8, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-07-25', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 70, 72, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-09-19', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 86, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 주인분들에게 감사합니다.', '2020-01-06', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 53, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 좋은 날씨에 오세요', '2020-02-15', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 61, 34, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2019-08-24', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 40, 18, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2020-02-18', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 46, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-03-13', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 34, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-02-19', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 62, 5, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 주인분들에게 감사합니다.', '2020-12-30', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 72, 83, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-09-29', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 64, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2019-01-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 63, 70, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-08-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 64, '최고의 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-11-05', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 19, '최고의 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2020-10-07', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 16, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2020-03-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 67, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-04-18', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 56, '최고의 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 주인분들에게 감사합니다.', '2020-11-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 41, '눈에 담고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-10-20', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 47, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-12-21', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 52, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-03-02', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 86, 25, '최고의 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2019-08-20', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 98, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-09-21', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 28, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-02-16', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 66, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-12-01', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 84, 25, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-08-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 12, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-11-14', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 46, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-08-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 83, 57, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-09-22', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 6, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2020-12-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 5, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2020-12-28', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 2, 62, '아름다운 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-11-27', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 84, 72, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-08-30', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 96, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-05-04', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 32, '눈에 담고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 청결이 좋습니다. 주인분들에게 감사합니다.', '2019-06-14', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 22, 33, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-04-24', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 93, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-08-01', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 28, '아름다운 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2019-09-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 12, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-11-10', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 90, 94, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-05-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 50, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-02-06', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 84, '최고의 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-07-05', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 22, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2020-12-31', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 78, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-02-02', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 15, 61, '추천하지 않습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-10-04', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 74, 39, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-01-30', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 38, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2020-01-26', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 73, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-05-21', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 57, 17, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-12-11', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 6, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-12-11', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 32, '최고의 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2019-05-06', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 51, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-07-06', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 81, 60, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-05-19', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 14, 67, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-04-20', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 42, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-07-10', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 47, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-07-27', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 90, 68, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-12-13', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 86, 60, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-12-24', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 81, 66, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-07-25', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 37, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-12-08', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 71, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-04-11', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 21, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-01-14', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 14, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-10-16', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 62, 74, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-02-27', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 80, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-07-10', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 56, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2019-11-28', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 69, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-12-20', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 83, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-10-13', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 84, 71, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-04-18', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 34, '눈에 담고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-08-25', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 74, 86, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-09-14', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 90, '최고의 식당입니다. 사랑하는 사람과 함께 오세요. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2019-03-30', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 57, 66, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-08-23', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 12, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-12-26', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 71, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2019-06-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 2, 23, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-07-23', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 34, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-05-23', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 54, 83, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-08-12', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 4, '최고의 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2019-01-10', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 41, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-14', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 13, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-05-30', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 73, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-11-18', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 99, 5, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-04-19', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 74, 60, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-03-12', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 90, 26, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-03-31', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 84, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-04-15', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 32, 78, '최고의 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-10-27', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 38, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-09-19', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 2, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-11-23', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 62, 76, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-01-01', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 36, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-07-30', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 64, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-12-03', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 25, '최고의 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-03-15', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 81, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-02-24', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 59, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-07-24', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 22, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-04-17', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 15, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-10-09', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 5, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 좋은 날씨에 오세요', '2020-08-28', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 83, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 주인분들에게 감사합니다.', '2019-01-29', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 45, 19, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-01-23', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 51, 49, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2020-08-04', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 56, 82, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 주인분들에게 감사합니다.', '2020-02-14', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 45, 41, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 주인분들에게 감사합니다.', '2020-09-03', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 36, '최고의 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-05-09', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 17, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-02-24', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 15, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-07-20', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 40, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-09-22', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 55, 10, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-08-10', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 9, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-01-25', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 86, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-05-24', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 11, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-11-21', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 77, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-04-29', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 91, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-02-22', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 12, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-03-15', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 92, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2020-10-14', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 42, 63, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-07-13', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 97, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-07-15', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 63, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-09-26', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 38, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-06-22', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 27, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-09-22', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 72, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-03-02', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 65, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-09-17', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 82, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-02-06', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 1, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-01-23', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 26, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 주인분들에게 감사합니다.', '2019-12-16', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 42, 72, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2019-02-03', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 40, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-12-20', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 15, 8, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-05-07', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 70, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-10-10', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 34, 9, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2019-04-30', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 11, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-01-05', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 91, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-02-16', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 8, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-06-14', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 84, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-06-22', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 57, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-02-16', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 80, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-01-20', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 8, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2019-01-21', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 80, 16, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-03-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 6, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-08-23', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 1, 20, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-10-31', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 100, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-10-29', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 82, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-01-20', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 27, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-12-08', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 93, 71, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-06-15', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 47, '최고의 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-06-19', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 43, '최고의 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-12-14', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 63, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-09-22', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 7, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-09-28', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 22, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 즐거운 하루가 되었어요', '2020-09-13', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 53, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2019-06-21', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 51, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-08-15', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 35, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-10-29', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 15, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-03-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 97, 29, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-08-18', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 23, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-10-29', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 41, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-01-06', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 86, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2019-09-27', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 1, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-08-28', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 17, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-09-15', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 4, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-12-18', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 19, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-01-06', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 37, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-04-27', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 22, 46, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-09-15', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 2, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-07-26', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 46, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-07-01', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 10, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-08-28', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 14, 55, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-01-04', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 39, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-09-25', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 38, 80, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2020-12-21', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 49, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-08-12', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 31, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 주인분들에게 감사합니다.', '2019-11-10', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 10, 60, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-09-24', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 83, 88, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-05-01', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 97, 7, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-07-05', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 49, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-01-06', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 75, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-12-17', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 69, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-01-23', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 86, 65, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-07-18', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 19, 93, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2019-01-11', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 48, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-06-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 51, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-03-18', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 42, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-12-22', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 86, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-04-09', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 55, '추천하지 않습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-03-30', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 63, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-07-26', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 83, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-04-26', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 32, 34, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-03-05', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 88, 22, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-04-28', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 43, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2019-09-16', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 75, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2019-03-28', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 6, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-05-26', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 78, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-05-11', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 67, 30, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2019-05-15', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 81, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-04-03', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 64, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-10-26', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 91, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2019-04-11', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 93, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-01-05', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 68, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-06-15', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 16, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2019-06-24', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 98, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2020-08-14', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 22, 29, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 청결이 좋습니다. 주인분들에게 감사합니다.', '2020-08-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 57, 29, '아름다운 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-08-29', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 55, 51, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-10-06', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 61, 47, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-09-18', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 3, 35, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-09-07', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 42, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-01-03', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 72, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-08-29', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 34, 67, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-11-22', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 51, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 주인분들에게 감사합니다.', '2019-11-15', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 61, 48, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2020-04-13', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 38, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 주인분들에게 감사합니다.', '2019-02-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 72, 15, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-09-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 52, 19, '최고의 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 좋은 날씨에 오세요', '2019-11-30', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 90, 46, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2020-07-23', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 71, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-12-31', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 34, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2019-11-25', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 72, 85, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-11-18', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 28, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-01-13', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 80, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-04-14', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 61, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-05-15', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 71, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-03-25', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 45, 92, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 주인분들에게 감사합니다.', '2020-08-30', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 40, 26, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-04-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 20, 89, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-07-25', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 45, 74, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-09-13', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 71, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2020-04-29', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 28, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-03-17', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 14, 21, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-04-02', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 37, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-08-22', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 83, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-04-25', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 2, 5, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-03-02', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 79, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-04-18', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 8, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2019-03-21', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 16, 60, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-02-16', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 7, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-11-29', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 33, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-06-04', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 95, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-05-06', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 39, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-11-19', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 57, 9, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-12-21', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 33, 12, '아름다운 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 주인분들에게 감사합니다.', '2020-01-01', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 2, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2020-05-19', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 51, 30, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2020-04-28', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 4, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-06-17', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 24, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-10-21', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 88, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2019-05-02', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 97, 26, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 즐거운 하루가 되었어요', '2019-02-18', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 13, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2019-11-17', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 50, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-03-26', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 66, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-04-02', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 38, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-10-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 54, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-02-16', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 56, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-03-08', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 60, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-07-27', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 21, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2020-04-01', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 69, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-03-16', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 18, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-08-02', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 50, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-07-20', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 45, 68, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-10-29', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 27, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-03-18', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 72, 71, '아름다운 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2020-03-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 83, 80, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-08-13', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 16, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2020-12-10', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 86, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-12-13', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 1, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-05-07', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 62, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-04-24', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 32, 20, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-10-16', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 62, 32, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-03-28', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 74, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-12-29', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 70, 69, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-04-12', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 91, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2020-05-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 17, 53, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-12-20', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 59, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2020-12-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 20, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 즐거운 하루가 되었어요', '2020-10-06', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 28, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2020-12-18', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 92, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2019-10-19', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 77, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-08-10', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 100, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-03-14', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 3, 90, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-07-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 27, '아름다운 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 주인분들에게 감사합니다.', '2020-07-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 62, '눈에 담고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-04-03', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 54, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-03-20', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 42, 43, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-11-08', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 46, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2020-03-27', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 16, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-22', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 97, 29, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-12-18', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 18, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-12-03', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 87, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-02-11', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 58, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-06-17', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 6, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2019-11-20', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 97, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-01-29', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 31, 35, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2020-08-17', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 94, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-08-22', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 87, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-06-05', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 15, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-04-24', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 2, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-07-28', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 9, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-04-13', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 25, 35, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-12-21', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 83, 66, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-03-20', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 95, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-08-12', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 54, 87, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-06-04', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 96, 65, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-12-06', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 1, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-04-22', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 14, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2020-08-15', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 71, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-11-10', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 78, 74, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-01-09', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 25, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2020-12-20', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 15, 39, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-01-11', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 63, 38, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-10-10', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 19, 39, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-11-26', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 50, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 즐거운 하루가 되었어요', '2020-10-26', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 83, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-06-21', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 32, 65, '아름다운 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-09-16', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 24, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-07-23', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 96, 5, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-02-20', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 30, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-06-15', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 39, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-09-18', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 28, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2019-12-15', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 32, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-11-04', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 16, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-06-08', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 12, 99, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-12-08', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 17, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-04-03', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 93, 69, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-09-04', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 5, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-06-07', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 37, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-10-25', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 59, 54, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-04-07', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 51, 71, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변이 깨끗해요 좋은 날씨에 오세요', '2020-12-01', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 75, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-08-01', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 91, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-03-17', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 19, 36, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-06-23', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 64, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2019-04-20', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 77, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-08-21', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 61, 77, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-11-08', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 32, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 즐거운 하루가 되었어요', '2020-05-01', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 49, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 주인분들에게 감사합니다.', '2020-09-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 3, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2019-12-15', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 66, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-10-06', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 4, 20, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 식당입니다.', '2020-07-09', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 98, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-07-29', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 26, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2020-06-17', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 36, 65, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-08-25', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 8, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2019-05-13', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 27, 60, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-03-08', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 45, '추천하지 않습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-03-15', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 28, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-02-13', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 71, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 주인분들에게 감사합니다.', '2019-09-11', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 38, 36, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-02-14', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 57, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-10-25', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 54, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-12-30', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 29, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 주인분들에게 감사합니다.', '2019-06-08', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 16, 75, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-01-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 81, 51, '추천하지 않습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-08-03', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 91, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-09-08', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 14, 41, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 주인분들에게 감사합니다.', '2020-12-16', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 34, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-01-29', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 86, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2020-04-30', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 100, 47, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-06-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 11, 48, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2020-03-19', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 77, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-04-29', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 52, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2019-04-17', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 33, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-07-29', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 8, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-09-03', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 47, 85, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2019-06-20', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 95, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-11-30', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 20, 27, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-11-30', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 79, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2020-04-02', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 35, '아름다운 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-05-11', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 52, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-07-06', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 1, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-03-12', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 34, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-06-26', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 20, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-04-15', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 72, 27, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-01-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 38, 94, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-12-31', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 59, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2019-09-24', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 38, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-12-28', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 62, 58, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-07-01', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 55, 40, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-07-02', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 21, 16, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2020-09-30', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 88, 50, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-02-21', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 24, 5, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-06-14', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 97, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-10-14', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 84, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-06-04', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 27, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-12-14', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 63, 27, '최고의 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-09-09', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 53, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 주인분들에게 감사합니다.', '2020-03-17', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 15, '너무 추천하는 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-06-01', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 45, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-12-18', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 16, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-01-06', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 63, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 주인분들에게 감사합니다.', '2019-02-20', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 40, 34, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-05-08', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 88, 77, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-01-02', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 46, 62, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-22', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 15, 2, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-07-15', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 86, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-11-28', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 38, 84, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-08-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 6, 61, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2020-03-24', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 97, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 주인분들에게 감사합니다.', '2020-07-28', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 78, 12, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 주인분들에게 감사합니다.', '2020-11-09', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 21, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-07-01', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 54, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2020-11-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 2, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2020-01-26', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 83, 66, '눈에 담고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-04-19', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 100, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-03-12', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 65, 17, '아름다운 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 주인분들에게 감사합니다.', '2019-02-26', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 7, 16, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-08-02', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 13, 90, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-11-09', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 2, 43, '아름다운 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2020-08-08', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 25, '너무 추천하는 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-03-23', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 36, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-01-11', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 95, 42, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-10-31', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 6, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-09-07', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 74, 52, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-11-23', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 91, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-01-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 87, 34, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-06-04', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 3, 32, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-05', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 47, '최고의 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-04-20', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 30, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-10-29', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 40, 86, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-01-25', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 39, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 청결이 좋습니다. 즐거운 하루가 되었어요', '2020-10-30', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 20, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변이 깨끗해요 즐거운 하루가 되었어요', '2020-10-28', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 13, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2020-07-22', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 22, 62, '눈에 담고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-08-16', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 92, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-12-25', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 61, 2, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2019-11-28', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 38, 68, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2020-03-06', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 56, 40, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-07-31', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 72, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-05-30', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 8, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-07-21', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 19, 38, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2020-01-09', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 53, 100, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2019-11-30', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 69, 37, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-12-01', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 51, 90, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-09-17', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 16, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-01-03', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 72, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-06-17', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 30, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-08-16', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 42, 3, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2019-11-02', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 37, 61, '여러 번 방문한 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-11-16', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 32, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 좋은 날씨에 오세요', '2020-02-03', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 40, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-07-04', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 83, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-07-29', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 97, 66, '눈에 담고 싶은 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-09-09', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 53, '다시 방문하고 싶은 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-04-18', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 39, 95, '여러 번 방문한 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-06-25', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 23, 55, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 주변이 깨끗해요 좋은 날씨에 오세요', '2020-07-10', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 17, 92, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 주인분들에게 감사합니다.', '2019-02-06', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 11, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-02-03', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 10, 7, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2019-12-03', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 17, 25, '아름다운 식당입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-05-17', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 98, 82, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-08-21', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 72, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 즐거운 하루가 되었어요', '2020-08-10', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 80, 58, '아름다운 식당입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 식당입니다.', '2020-06-24', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 4, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-27', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 48, 65, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-02-05', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 56, 62, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-03-28', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 34, 66, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-03-01', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 96, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-03-09', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 85, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 주변에 구경거리가 있어요 나만 알고 싶은 식당입니다.', '2019-02-04', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 41, '여러 번 방문한 식당입니다. 사랑하는 사람과 함께 오세요. 주변이 깨끗해요 날씨도 좋고 너무 좋아요', '2020-11-03', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 76, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-12-16', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 94, 99, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 즐거운 하루가 되었어요', '2020-10-02', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 30, '최고의 식당입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-10-18', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 42, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-04-06', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 32, 58, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2019-08-29', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 43, 100, '다시 방문하고 싶은 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 주인분들에게 감사합니다.', '2019-06-02', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 41, 87, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-02-02', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 64, '재방문은 없습니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2019-05-26', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 16, 77, '별로인 식당입니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-12-15', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 59, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-06-01', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 73, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-04-15', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 71, 43, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-02-24', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 26, 100, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2019-10-28', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 5, 30, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-03-12', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 25, 99, '별로인 식당입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-06-10', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 91, 88, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2020-02-06', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 64, 73, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-04-07', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 89, 63, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-01-07', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 51, 12, '가기 좋은 식당입니다. 부모님을 모시고 오고 싶습니다. 주변이 깨끗해요 나만 알고 싶은 식당입니다.', '2020-11-23', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 76, 8, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-11-18', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 96, 68, '여러 번 방문한 식당입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-10-01', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 68, 48, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-02-27', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 85, 36, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 청결이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-08-02', 5);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 40, 7, '최고의 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-04-03', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 35, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-09-18', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 28, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-05-22', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 33, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-11-22', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 86, 97, '최고의 식당입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-08-27', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 8, 84, '다시 방문하고 싶은 식당입니다. 애인과 함께 오고 싶어요 주변이 깨끗해요 행복한 시간을 가졌습니다.', '2019-04-27', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 75, 41, '아름다운 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-05-16', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 34, 52, '별로인 식당입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-10-05', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 15, 57, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-09-14', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 80, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 날씨도 좋고 너무 좋아요', '2020-09-26', 9);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 73, '다시 방문하고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 나만 알고 싶은 식당입니다.', '2019-09-03', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 77, 95, '너무 추천하는 식당입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-03-18', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 79, 65, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-04-19', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 73, 68, '가기 좋은 식당입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 주인분들에게 감사합니다.', '2019-08-02', 7);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 53, '여러 번 방문한 식당입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-06-27', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 82, 61, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-02-07', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 58, 71, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-12-03', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 29, 89, '가기 좋은 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 즐거운 하루가 되었어요', '2019-05-17', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 49, '별로인 식당입니다. 누구 데려가면 욕먹을 듯. 주인분들도 그냥 그래요.', '2019-02-28', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 35, 68, '가기 좋은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 즐거운 하루가 되었어요', '2019-10-06', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 30, 58, '너무 추천하는 식당입니다. 사랑하는 사람과 함께 오세요. 청결이 좋습니다. 행복한 시간을 가졌습니다.', '2020-01-04', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 92, 88, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주인분들도 그냥 그래요.', '2020-09-11', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 56, 90, '가기 좋은 식당입니다. 친구들과 함께 오기 좋습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2020-11-22', 6);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 28, 25, '최고의 식당입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-09-02', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 50, 38, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-10-26', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 66, 49, '다시 방문하고 싶은 식당입니다. 사랑하는 사람과 함께 오세요. 주변에 구경거리가 있어요 좋은 날씨에 오세요', '2020-03-13', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 60, 82, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-03-26', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 9, 65, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-03-20', 2);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 63, 47, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-09-09', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 3, 53, '최고의 식당입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 주인분들에게 감사합니다.', '2019-07-23', 8);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 49, 81, '최고의 식당입니다. 애인과 함께 오고 싶어요 주변에 구경거리가 있어요 행복한 시간을 가졌습니다.', '2019-09-21', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 20, 80, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-08-12', 4);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 67, 97, '너무 추천하는 식당입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 식당입니다.', '2019-02-28', 10);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 59, 79, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-10-02', 1);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 44, 76, '별로인 식당입니다. 갈꺼면 혼자가세요. 주인분들도 그냥 그래요.', '2020-11-21', 3);
INSERT INTO tblRestaurantReview VALUES(seqRestaurantReview.nextVal, 18, 61, '눈에 담고 싶은 식당입니다. 아이들과 함께 오고 싶습니다. 청결이 좋습니다. 좋은 날씨에 오세요', '2019-11-13', 10);
