INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 40, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-08-30', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 1, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-06-30', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 24, 85, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-04-29', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 65, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-20', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 98, 76, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-06-19', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 45, '추천하지 않습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-05-22', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 59, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-11-27', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 29, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-08-30', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 100, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-10-21', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 2, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-09-20', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 31, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-07-15', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 76, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-05-30', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 59, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2020-11-23', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 12, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2019-09-26', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 38, 7, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-06-01', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 42, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-03-30', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 8, 2, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-06-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 43, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-01-09', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 95, 6, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-30', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 63, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2019-04-11', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 20, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-04-14', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 39, '최고의 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-05-16', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 17, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-04-23', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 22, 52, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2019-03-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 24, 75, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-03-26', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 13, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2020-07-05', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 6, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-04-26', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 79, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-03-17', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 21, 25, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-01-22', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 97, 12, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 즐거운 하루가 되었어요', '2019-11-02', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 10, 51, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-09-15', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 29, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-06-01', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 93, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-10-11', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 30, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-09-29', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 38, 47, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2019-04-23', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 88, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-11-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 42, 51, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-07-14', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 37, '아름다운 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2019-06-07', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 26, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-12-18', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 19, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-10-28', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 35, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 좋은 날씨에 오세요', '2019-08-25', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 54, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-12-18', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 69, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-01-30', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 63, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-01-16', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 26, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-09-18', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 90, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-05-14', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 30, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-10-21', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 51, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-05-19', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 68, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-06-05', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 7, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-07-24', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 83, 4, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-01-31', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 88, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-01-22', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 77, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-10-15', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 42, 77, '아름다운 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-09-23', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 89, 19, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-11-07', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 50, 43, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-11-09', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 96, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-07-11', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 97, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-04-21', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 89, 33, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-08-01', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 45, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2020-06-12', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 2, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 좋은 날씨에 오세요', '2019-03-11', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 9, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-02-28', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 40, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-01-12', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 51, 74, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-07-08', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 98, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-03-31', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 97, 80, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-07-05', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 89, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-01-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 10, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-01-20', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 7, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-05-31', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 91, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-06-08', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 64, 48, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2020-03-14', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 8, 6, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-04-24', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 34, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-01-23', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 74, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2019-03-09', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 83, 82, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', '2020-03-05', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 54, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-12-05', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 74, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-02-13', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 48, 44, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-13', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 34, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-06-15', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 80, 78, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2020-03-05', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 100, 12, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-04-17', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 97, 3, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-06-05', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 2, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-02-16', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 52, 5, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-10-16', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 28, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-07-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 95, 84, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2019-06-21', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 36, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2019-02-20', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 38, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-04-15', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 20, 75, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-04-28', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 79, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-11-17', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 93, 41, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-08-31', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 87, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-11-12', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 73, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-05-04', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 99, 28, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-04-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 82, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-11-21', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 90, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 좋은 날씨에 오세요', '2020-03-20', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 96, 46, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-12-26', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 29, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-08-07', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 48, 40, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2020-12-01', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 8, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-11-09', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 78, '아름다운 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-06-19', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 81, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-08', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 3, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-03-05', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 94, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-06-04', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 96, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 좋은 날씨에 오세요', '2019-03-25', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 86, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2020-06-05', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 18, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-05-30', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 29, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-01-10', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 71, '최고의 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-07-30', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 50, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2019-07-22', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 91, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2020-09-13', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 95, 9, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-02-15', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 14, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-08-08', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 8, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-05-04', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 95, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-01-26', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 91, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2019-08-24', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 59, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 즐거운 하루가 되었어요', '2019-09-18', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 3, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-07-05', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 38, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-01-05', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 61, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2019-03-18', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 78, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-04-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 10, 59, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-03-19', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 100, 69, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-02-09', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 79, 96, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2019-07-21', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 7, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-07-17', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 21, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-04-24', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 29, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2020-09-11', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 48, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-03-02', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 26, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-05-14', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 80, 80, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2019-03-03', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 98, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-09-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 24, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2019-02-07', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 99, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2019-05-08', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 35, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-24', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 13, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-04-10', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 54, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-05-08', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 62, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-07-14', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 17, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-02-28', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 37, 63, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-03-18', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 21, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2019-06-20', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 37, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-08-07', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 45, '최고의 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 좋은 날씨에 오세요', '2020-07-08', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 81, 4, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-02-03', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 28, 1, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-11-28', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 89, 83, '최고의 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-04-26', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 72, 41, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-07-27', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 83, 50, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-06-11', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 34, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-12-18', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 32, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-08-18', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 86, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-11-17', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 25, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-09-03', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 100, 25, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-07-17', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 78, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-11-17', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 32, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-09-18', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 9, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-04-10', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 69, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-06-24', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 52, 28, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2019-04-24', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 42, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-11-11', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 64, 61, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2020-02-14', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 15, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-01-07', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 69, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-10-18', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 71, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2019-08-25', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 97, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-05-03', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 25, 13, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2019-02-03', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 4, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-11-01', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 53, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-09-19', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 79, 14, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-09-14', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 13, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-06-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 50, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-01-10', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 42, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-06-28', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 14, 77, '아름다운 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-04-26', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 80, 16, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-08-13', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 76, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-03-15', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 34, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2019-09-16', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 75, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-07-13', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 5, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-04-07', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 33, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2020-07-19', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 82, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-06-11', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 19, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-04-03', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 22, 99, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2019-09-29', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 37, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-01-12', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 29, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-10-19', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 84, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2020-12-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 22, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-02-09', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 86, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-09-24', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 20, 58, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-12-17', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 12, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-01-26', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 21, 80, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-07-26', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 81, 97, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2019-03-08', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 37, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2019-02-24', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 81, 78, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-03-30', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 2, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2019-10-20', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 77, 35, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 관리자분들에게 감사합니다.', '2020-02-07', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 47, 34, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-10-09', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 42, 40, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-10-02', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 23, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 좋은 날씨에 오세요', '2019-11-03', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 99, 50, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-01-15', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 24, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-04-25', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 31, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-04-04', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 69, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-04-22', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 75, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-04-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 30, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-01-02', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 31, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2020-06-05', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 66, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-11-02', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 37, 50, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-02-12', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 37, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-12-05', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 48, 50, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-04-02', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 7, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-03-12', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 25, 70, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-07-26', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 59, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-02-24', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 55, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 즐거운 하루가 되었어요', '2019-08-05', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 91, '최고의 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 관리자분들에게 감사합니다.', '2020-04-04', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 5, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-01-17', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 17, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 관리자분들에게 감사합니다.', '2020-11-18', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 58, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-12-25', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 2, 72, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-04-21', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 97, '최고의 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 좋은 날씨에 오세요', '2020-01-27', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 60, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-12-25', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 72, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-11-29', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 71, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-02-17', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 2, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-06-20', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 22, 12, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-05-25', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 88, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-04-27', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 65, 33, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-10-01', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 92, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-01-23', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 39, 7, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-12-13', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 4, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-04-18', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 73, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-03-01', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 81, 55, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2020-02-23', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 89, 92, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-11-30', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 61, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-04-05', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 31, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2019-08-06', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 64, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-04-24', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 41, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-12-25', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 76, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-04-07', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 50, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-05-17', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 89, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2019-11-08', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 90, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-03-21', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 42, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-10-04', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 73, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-07-08', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 71, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-07-20', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 41, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2019-07-26', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 7, 7, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-12-10', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 14, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-02-11', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 70, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-04-22', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 46, 82, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-05-28', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 52, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2019-10-01', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 57, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-04-17', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 39, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 좋은 날씨에 오세요', '2019-10-11', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 65, 30, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-06-29', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 87, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2019-06-10', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 28, 51, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-05-26', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 55, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-09-20', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 54, 43, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-03-29', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 54, 25, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-03-13', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 14, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-02-23', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 36, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-11-23', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 2, 42, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-06-08', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 86, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2019-08-20', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 99, 58, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-08-29', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 66, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2019-08-15', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 7, 15, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-25', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 35, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-12-14', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 87, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2020-06-26', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 81, 6, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-09-17', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 57, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-04-25', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 77, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2019-10-21', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 16, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-04-19', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 69, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-03-31', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 42, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-04-05', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 97, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-03-22', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 74, 64, '추천하지 않습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-04-07', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 14, 86, '재방문은 없습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-03-03', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 98, 29, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-05-12', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 62, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', '2020-07-12', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 21, 65, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-04-21', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 84, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-02-10', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 80, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-12-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 48, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-04-06', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 31, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2020-11-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 62, 97, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2019-05-13', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 20, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-01-28', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 23, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-10-19', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 60, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-09-02', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 100, 81, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2019-01-22', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 5, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 좋은 날씨에 오세요', '2020-05-27', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 74, 15, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-03-13', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 91, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', '2020-02-13', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 40, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-03', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 95, 87, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-06-20', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 30, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-08-30', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 79, 2, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-10-14', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 65, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-07-26', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 11, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-06-30', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 2, 21, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-04-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 1, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-03-21', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 79, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-04-08', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 20, 90, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-06-30', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 71, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2020-08-05', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 57, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2020-01-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 70, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-05-07', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 23, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-12-26', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 54, 77, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-01-16', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 80, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-03-04', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 87, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-06-16', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 18, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2020-06-03', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 45, 83, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2019-04-01', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 27, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-10-15', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 48, 95, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2019-01-07', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 89, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-04-10', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 43, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-09-29', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 10, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-02-13', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 75, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2019-05-07', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 28, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2019-06-21', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 94, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2020-09-04', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 44, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-11-09', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 14, 40, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-03-16', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 80, 5, '아름다운 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 좋은 날씨에 오세요', '2019-05-20', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 50, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 좋은 날씨에 오세요', '2020-02-08', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 99, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-05-03', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 41, 90, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2020-11-03', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 42, 5, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-05-13', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 82, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-10-14', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 41, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-10-27', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 46, 9, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-01-19', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 15, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-06-17', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 61, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2019-11-17', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 12, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2020-12-18', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 88, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-07-20', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 44, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-09-19', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 83, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-03-16', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 55, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-11-30', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 17, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2020-02-23', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 72, 82, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 좋은 날씨에 오세요', '2019-03-01', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 7, 53, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-01-08', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 44, 12, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-02-04', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 40, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-08-26', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 86, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-01-17', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 62, 29, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2020-02-27', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 60, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-12-28', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 15, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-10-14', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 51, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-09-05', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 35, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-11-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 35, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-09-03', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 46, 63, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-12-23', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 45, 98, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-09-28', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 48, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-01-29', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 84, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-02-13', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 81, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-01-15', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 67, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-07-23', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 8, 5, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-03-09', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 90, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-01-09', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 23, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-11-20', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 78, 90, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-01-06', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 92, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-02-10', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 72, 87, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-03-05', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 14, '최고의 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-05-02', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 28, 76, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-12-30', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 14, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-02-12', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 6, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-01-20', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 72, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2019-04-10', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 97, 39, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', '2019-08-06', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 17, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-10-25', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 26, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-03', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 91, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2019-10-13', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 31, '아름다운 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2020-10-21', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 100, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-01-03', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 55, 75, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2019-05-19', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 9, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-02-28', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 96, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-04-22', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 73, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-03-06', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 40, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-12-28', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 40, 100, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-10-23', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 7, 87, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-09-14', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 56, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2020-06-15', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 80, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2019-03-01', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 20, 36, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-02-06', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 91, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', '2019-04-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 86, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2019-11-10', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 89, 65, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2019-07-14', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 47, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-02-21', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 24, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-04-30', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 99, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-06-06', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 43, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-06-05', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 39, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2019-12-17', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 84, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-06-28', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 50, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-08-21', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 45, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-08-19', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 65, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-26', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 40, 61, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-01-09', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 96, 65, '추천하지 않습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-10-25', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 75, 6, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-02-18', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 27, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-06-26', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 21, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 관리자분들에게 감사합니다.', '2020-07-28', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 39, 70, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2020-04-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 11, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-04-25', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 7, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2020-07-23', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 46, 32, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-06-12', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 52, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-10-13', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 56, 55, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 관리자분들에게 감사합니다.', '2020-05-30', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 53, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2019-01-17', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 24, 87, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-07-17', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 68, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2019-10-04', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 22, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-02-16', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 3, 85, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-04-14', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 12, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-05-25', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 68, 14, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-02-09', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 89, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-03-10', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 62, 60, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-04-11', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 27, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-05-21', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 42, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-11-27', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 45, 77, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-07-17', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 10, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2019-03-13', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 29, 75, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-09-19', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 8, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-11-28', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 70, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-04-27', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 30, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-11-06', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 42, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2020-05-05', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 90, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-01-20', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 37, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 좋은 날씨에 오세요', '2019-05-01', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 36, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 즐거운 하루가 되었어요', '2019-03-01', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 3, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-08-24', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 53, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-11-30', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 2, 26, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2019-09-11', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 22, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2020-10-16', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 52, 28, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-05-28', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 28, 53, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2019-11-01', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 42, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-11-21', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 7, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2019-01-22', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 90, 45, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2019-10-31', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 100, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2019-06-19', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 22, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2020-03-12', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 55, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-07-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 100, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-03-24', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 37, 70, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-07-09', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 82, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', '2019-10-10', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 93, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-08-21', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 37, 80, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-11-28', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 74, 78, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2019-06-09', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 55, 51, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 행복한 시간을 가졌습니다.', '2020-07-15', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 27, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-08-22', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 64, 36, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2019-09-17', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 9, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2019-02-13', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 56, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2020-11-01', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 66, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2019-06-19', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 92, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-01-05', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 11, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-01-23', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 99, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2020-03-01', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 18, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-03-31', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 8, 59, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 좋은 날씨에 오세요', '2019-12-14', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 18, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-04-11', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 74, 15, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-23', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 47, 52, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2019-07-05', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 81, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2020-10-12', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 20, 31, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-05-17', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 86, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-12-09', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 34, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-03-15', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 86, 80, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-04-15', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 84, '최고의 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 즐거운 하루가 되었어요', '2020-11-28', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 24, 44, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2020-04-04', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 5, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2019-11-18', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 57, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-05-29', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 47, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-12-14', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 31, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-08-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 38, 1, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2019-06-13', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 38, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-08-31', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 38, 11, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-06-17', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 39, 56, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-03-02', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 24, 92, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-11-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 44, 16, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-12-12', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 17, '최고의 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2020-08-31', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 99, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-04-19', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 100, 71, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', '2020-02-06', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 52, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-01-02', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 30, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', '2020-02-26', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 49, 23, '아름다운 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-05-11', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 57, 32, '별로인 장소입니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-09-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 11, 36, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2019-11-18', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 71, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-11-13', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 22, 71, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-12-06', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 63, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-08-04', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 26, 42, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-08-29', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 94, 83, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-02', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 95, '추천하지 않습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-12-16', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 31, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 좋은 날씨에 오세요', '2019-02-28', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 37, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 관리자분들에게 감사합니다.', '2019-10-14', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 85, 20, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2020-03-06', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 54, 66, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-04-03', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 15, '최고의 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2020-10-25', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 35, 71, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-06-03', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 85, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-09-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 88, 46, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 나만 알고 싶은 장소입니다.', '2020-03-15', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 6, 15, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-05-09', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 5, 35, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-12-26', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 25, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', '2019-10-23', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 43, 67, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2019-04-06', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 13, 84, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-01-13', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 72, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2019-11-14', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 4, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2019-03-23', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 46, 34, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2019-09-12', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 14, 73, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 나만 알고 싶은 장소입니다.', '2019-06-08', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 52, 68, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2019-08-04', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 62, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-04-01', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 10, 15, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2019-12-04', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 55, 66, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-02-14', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 25, 96, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', '2019-11-27', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 62, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2020-01-21', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 8, 45, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-10-08', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 29, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2020-10-14', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 22, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 즐거운 하루가 되었어요', '2019-07-09', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 80, 8, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2019-08-21', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 6, 37, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2019-10-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 60, 72, '다시는 안 갈 것 같아요 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-08-21', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 55, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-09-06', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 39, 80, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-06-24', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 72, 30, '별로인 장소입니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-07-16', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 74, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 관리자분들에게 감사합니다.', '2020-12-15', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 64, 67, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-09-05', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 26, 74, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', '2019-05-09', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 33, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2020-12-12', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 38, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-12-31', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 71, 94, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', '2019-03-23', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 8, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', '2019-08-03', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 98, 16, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-01-08', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 46, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-11-25', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 59, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 관리자분들에게 감사합니다.', '2019-03-18', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 62, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2019-03-22', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 6, 52, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 관리자분들에게 감사합니다.', '2019-06-13', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 34, 17, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-08-26', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 35, 32, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2019-04-01', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 38, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 관리자분들에게 감사합니다.', '2020-09-13', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 82, 8, '너무 추천하는 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', '2020-07-14', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 61, 27, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', '2020-01-25', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 19, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', '2020-10-01', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 93, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 좋은 날씨에 오세요', '2019-05-27', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 90, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-12-12', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 45, 88, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-01-10', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 53, 77, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', '2020-11-29', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 27, 29, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-09-16', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 76, 7, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', '2019-10-14', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 14, 35, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', '2019-10-09', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 17, 12, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-08-29', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 57, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-07-07', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 17, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2019-01-01', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 24, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 좋은 날씨에 오세요', '2020-05-11', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 95, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-08-20', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 100, '별로인 장소입니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-11-29', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 99, 34, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 좋은 날씨에 오세요', '2020-08-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 72, 90, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-02-15', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 38, 41, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-12-29', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 83, 13, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2019-01-05', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 86, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-03-29', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 21, 48, '추천하지 않습니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-10-16', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 91, 66, '추천하지 않습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-09-13', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 18, 23, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', '2019-06-06', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 69, 78, '재방문은 없습니다. 누구 데려가면 욕먹을 듯. 관리자들도 그냥 그래요.', '2020-10-05', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 12, 69, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-09-25', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 83, 17, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', '2020-09-15', 10);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 63, 62, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', '2020-06-20', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 84, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-08-11', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 17, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2020-11-11', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 1, 83, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-10-30', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 70, 98, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 행복한 시간을 가졌습니다.', '2020-01-11', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 66, 4, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 주변 시설도 그닥', '2020-08-01', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 62, 92, '별로인 장소입니다. 누구 데려가면 욕먹을 듯. 리뷰 쓰는것도 귀찮네요.', '2020-12-12', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 59, 83, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2019-12-24', 7);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 93, 28, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2019-09-30', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 15, 98, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 즐거운 하루가 되었어요', '2020-06-30', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 73, 85, '다시는 안 갈 것 같아요 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2020-05-17', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 4, 83, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2019-07-03', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 36, 22, '재방문은 없습니다. 갈꺼면 혼자가세요. 관리자들도 그냥 그래요.', '2020-04-11', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 23, 5, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-04-10', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 58, 78, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-05-23', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 30, 32, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 좋은 날씨에 오세요', '2020-08-03', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 84, 1, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-10-15', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 35, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', '2019-09-05', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 98, 37, '재방문은 없습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-04-30', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 65, 56, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', '2019-08-09', 9);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 87, 8, '별로인 장소입니다. 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-01-21', 1);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 48, 13, '재방문은 없습니다. 갈꺼면 혼자가세요. 주변 시설도 그닥', '2019-04-25', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 9, 17, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 주변에 맛집이 있어요 좋은 날씨에 오세요', '2020-05-11', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 19, 87, '추천하지 않습니다. 누구 데려가면 욕먹을 듯. 주변 시설도 그닥', '2019-01-08', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 67, 43, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 리뷰 쓰는것도 귀찮네요.', '2020-05-19', 4);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 16, 44, '눈에 담고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', '2020-07-10', 6);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 92, 42, '다시는 안 갈 것 같아요 갈꺼면 혼자가세요. 리뷰 쓰는것도 귀찮네요.', '2020-09-28', 2);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 95, 98, '추천하지 않습니다. 사이 좋지 않은 사람과 함께~. 관리자들도 그냥 그래요.', '2020-09-19', 3);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 7, 49, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', '2020-08-16', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 33, 16, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', '2020-03-04', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 32, 13, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', '2020-03-11', 5);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 42, 18, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 즐거운 하루가 되었어요', '2020-01-21', 8);
INSERT INTO tblSpotReview VALUES(seqSpotReview.nextVal, 31, 16, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 행복한 시간을 가졌습니다.', '2020-11-11', 7);

