
INSERT INTO tblSpotList values (seqSpotList.nextVal, 1, 1, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 좋은 날씨에 오세요', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 5, 1, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 6, 1, '최고의 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 8, 1, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 9, 1, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 11, 1, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 14, 1, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 좋은 날씨에 오세요', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 15, 1, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 날씨도 좋고 너무 좋아요', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 18, 1, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 19, 1, '여러 번 방문한 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 관리자분들에게 감사합니다.', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 25, 2, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 행복한 시간을 가졌습니다.', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 26, 2, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 날씨도 좋고 너무 좋아요', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 31, 3, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 32, 3, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 직원들이 친절해요 즐거운 하루가 되었어요', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 33, 3, '아름다운 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 행복한 시간을 가졌습니다.', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 36, 4, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 37, 4, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 38, 4, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 날씨도 좋고 너무 좋아요', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 39, 4, '다시 방문하고 싶은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 즐거운 하루가 되었어요', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 40, 4, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 41, 4, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 즐거운 하루가 되었어요', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 42, 4, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 시설이 좋습니다. 좋은 날씨에 오세요', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 43, 4, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 46, 5, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 47, 5, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 48, 5, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 행복한 시간을 가졌습니다.', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 51, 6, '눈에 담고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 즐거운 하루가 되었어요', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 52, 6, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 53, 6, '눈에 담고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 54, 6, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 55, 6, '너무 추천하는 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 56, 7, '가기 좋은 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 좋은 날씨에 오세요', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 57, 7, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 58, 7, '가기 좋은 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 59, 7, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 관리자분들에게 감사합니다.', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 60, 7, '최고의 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 날씨도 좋고 너무 좋아요', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 61, 7, '다시 방문하고 싶은 장소입니다. 아이들과 함께 오고 싶습니다. 직원들이 친절해요 즐거운 하루가 되었어요', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 62, 7, '아름다운 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 63, 7, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 즐거운 하루가 되었어요', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 64, 7, '아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 65, 8, '너무 추천하는 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 66, 8, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 맛집이 있어요 즐거운 하루가 되었어요', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 67, 8, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 68, 8, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 화장실도 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 69, 8, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 좋은 날씨에 오세요', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 70, 8, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 행복한 시간을 가졌습니다.', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 71, 8, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 화장실도 좋습니다. 관리자분들에게 감사합니다.', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 72, 8,'아름다운 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 73, 8, '가기 좋은 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 맛집이 있어요 즐거운 하루가 되었어요', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 74, 8, '가기 좋은 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 날씨도 좋고 너무 좋아요', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 75, 8, '최고의 장소입니다. 아이들과 함께 오고 싶습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 76, 9, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 77, 9, '여러 번 방문한 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 나만 알고 싶은 장소입니다.', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 78, 9, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 화장실도 좋습니다. 행복한 시간을 가졌습니다.', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 79, 9, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 80, 9, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 81, 10, '너무 추천하는 장소입니다. 사랑하는 사람과 함께 오세요. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 82, 10, '아름다운 장소입니다. 애인과 함께 오고 싶어요 주변에 깨끗해요 좋은 날씨에 오세요', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 83, 10, '가기 좋은 장소입니다. 애인과 함께 오고 싶어요 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 84, 10, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 깨끗해요 즐거운 하루가 되었어요', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 85, 10, '여러 번 방문한 장소입니다. 친구들과 함께 오기 좋습니다. 관리가 잘 되어 있습니다. 행복한 시간을 가졌습니다.', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 86, 11, '다시 방문하고 싶은 장소입니다. 사랑하는 사람과 함께 오세요. 관리가 잘 되어 있습니다. 나만 알고 싶은 장소입니다.', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 87, 11, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 즐거운 하루가 되었어요', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 88, 11, '눈에 담고 싶은 장소입니다. 애인과 함께 오고 싶어요 직원들이 친절해요 날씨도 좋고 너무 좋아요', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 89, 11, '최고의 장소입니다. 사랑하는 사람과 함께 오세요. 직원들이 친절해요 좋은 날씨에 오세요', 'spot_05.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 90, 11, '아름다운 장소입니다. 아이들과 함께 오고 싶습니다. 시설이 좋습니다. 나만 알고 싶은 장소입니다.', 'spot_06.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 91, 11, '너무 추천하는 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', 'spot_07.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 92, 11, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', 'spot_08.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 93, 11, '다시 방문하고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 관리자분들에게 감사합니다.', 'spot_09.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 94, 11, '여러 번 방문한 장소입니다. 아이들과 함께 오고 싶습니다. 관리가 잘 되어 있습니다. 관리자분들에게 감사합니다.', 'spot_10.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 95, 11, '눈에 담고 싶은 장소입니다. 부모님을 모시고 오고 싶습니다. 화장실도 좋습니다. 좋은 날씨에 오세요', 'spot_01.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 96, 11, '다시 방문하고 싶은 장소입니다. 친구들과 함께 오기 좋습니다. 주변에 깨끗해요 나만 알고 싶은 장소입니다.', 'spot_02.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 97, 11, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 시설이 좋습니다. 행복한 시간을 가졌습니다.', 'spot_03.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 98, 11, '최고의 장소입니다. 부모님을 모시고 오고 싶습니다. 주변에 맛집이 있어요 관리자분들에게 감사합니다.', 'spot_04.jpg');
INSERT INTO tblSpotList values (seqSpotList.nextVal, 99, 11, '여러 번 방문한 장소입니다. 사랑하는 사람과 함께 오세요. 시설이 좋습니다. 날씨도 좋고 너무 좋아요', 'spot_05.jpg');
